name: CI latest

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    name: Build and publish image
    runs-on: ubuntu-latest

    steps:

      - name: 'Github: checkout'
        uses: actions/checkout@v3

      - name: 'Github: setup Node.js LTS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: 'TS Library: install'
        run: npm install

      - name: 'TS Library: build'
        run: npm run build

      - name: 'TS Library: publish'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
